language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer update --no-interaction --prefer-stable

script:
  - vendor/bin/phpunit --verbose
  - vendor/bin/php-cs-fixer fix --dry-run

matrix:
  fast_finish: true